### ISSUE TITLE
[SPO] Inconsistent numbers of synced documents between summary page and sync jobs

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#1567] opened 2023-09-04 12:48 UTC
## Bug Description
When sync ends, we show how many documents are in the index + how many were ingested/deleted.

These numbers almost never match.

### To Reproduce
1. Create an SPO connector and connector to our test instance
2. Run a sync
3. Observe the numbers on Overview page (Document count + Docs added in the table with syncs). They will not match

## Expected behavior
Document count on overview page makes sense: for example, if 1 sync happened and reported that 10000 documents were added, then Document count should show 10000, not 9993.

## Screenshots
![image](https://github.com/elastic/connectors-python/assets/12238374/c45cd0d6-ec58-474f-95f6-eb5f7ac6b2be)

## Additional context
This happens for Sharepoint Online connector, but might happen for other connectors as well.

**Comment by wangch079** [comment] 2023-09-06 17:22
Although the SPO sync always fail somehow after a certain period, I can reproduce this locally.

But I can confirm this is due to duplicated documents generated from the source implementation. I added a set to store unique document ids, and a counter to count the total documents (including duplicates). When it failed, I got below logs:

```shell
[FMWK][01:09:41][DEBUG] added doc_id 01XVLUAJIMS6FP2VMNPFHJGUMAHLFVRNFN, size of id set: 5239, total_count: 5397
[FMWK][01:09:41][DEBUG] stats after bulk api, size of id set: 5239, total_count: 5397, indexed_document_count: 5397
[FMWK][01:09:42][INFO] [Connector id: caona4oBE4OtGnN0l9Yh, index name: search-spo, Sync job id: eqpda4oBE4OtGnN0bNZZ] Sync ended with status error -- created: 5514 | updated: 0 | deleted: 0 (took 1765 seconds)
```

You can see different numbers from the above log:

1. 5239 is the unique number of documents indexed
2. 5397 is the total operations in the bulk api call
3. 5514 is the number of documents generated by `Extractor`.

Below is the screenshot:

![image](https://github.com/elastic/connectors-python/assets/54903978/f1582ed8-1b79-4d25-b30b-d5d32c016408)

You can see the numbers 5239 and 5397 matched, and you didn't see 5514 because we never use it (we only care how many documents are indexed, not fetched).

I don't think this is a bug. 5239 is the document count, which is correct. 5397 is the number of index operations, which is also correct, although it includes duplicates.

WDYT? cc @danajuratoni @artem-shelkovnikov

**Comment by artem-shelkovnikov** [comment] 2023-09-07 10:25
So a problem is that the documents have ids that are not unique, and I think it's a pretty big bug.

Did you manage to see which object types had duplicate ids @wangch079?

**Comment by wangch079** [comment] 2023-09-07 14:49
>Did you manage to see which object types had duplicate ids

OK, I think it works as expected at the framework-level. I will investigate further why duplicate documents are generated.

**Comment by artem-shelkovnikov** [comment] 2023-09-08 10:03
@wangch079 thinking of it more, do you think it would be reasonable for us to try to track the duplcate ids in the framework? 

I'm on the fence cause it's a memory hog, but we can also enable it only in some sort of "dev mode" for connectors - IMO it has a lot of value for cases when developing connectors

**Comment by wangch079** [comment] 2023-09-08 10:38
>do you think it would be reasonable for us to try to track the duplcate ids in the framework?

I was always expecting unique ids from `get_docs`, but is it a hard requirement? The framework should still work if there are duplicates, and the stats `indexed_document_count` and `indexed_document_volumes` reflect it correctly, IMO it's correct to counted as 2 and 2 KB if a 1 KB document is indexed twice.

**Comment by artem-shelkovnikov** [comment] 2023-09-08 10:45
Good point. I can see that actually working for some connectors!

**Comment by wangch079** [comment] 2023-09-08 16:34
> So a problem is that the documents have ids that are not unique, and I think it's a pretty big bug.
> 
> Did you manage to see which object types had duplicate ids

Hi @artem-shelkovnikov, I ran a sync job again, and found the duplicated documents are either `site_list` or `drive_item`. I tried to upload it to https://upload.elastic.co, but found that it's available for public download.

Do you have any idea what other fields in the documents are useful? I see one of the documents is `Shared Documents`, which makes me wonder whether it's because those items are shared. 

I tried to access the docs by `webUrl`, but it requires 2FA logging in as `demo@enterprisesearch.onmicrosoft.com`

**Comment by seanstory** [comment] 2023-09-14 19:17
Wanted to comment on this issue that another thing that makes these numbers look wrong is that nothing counts the number of documents we see on full sync that were:
- previously seen on a previous full sync
- have not changed since the previous full sync

This can lead to a sync job history like:
```
Date | Duration | Added | Updated | Deleted
2023-01-02 | 6 hours  | 5 | 3 | 0
2023-01-01 | 6 hours | 10000 | 0 | 0
```

Maybe we need another column like, "Fetched"?

**Comment by danajuratoni** [comment] 2023-09-18 08:10
Since these seem to be correct numbers, just counting different things, the critical part is to clearly communicate in Kibana what's counted. The confusion arises because the displayed numbers are "Document count" on index **vs.** "Docs added" (for each sync) implying we are counting the same thing - which is not the case!

**Comment by DianaJourdan** [comment] 2023-09-18 13:58
Agreed with the team to keep this ticket for 2 actions:
- investigate if there is a different way to display the numbers, so they are not confusing to the user
- update the signposting in Kibana / adding a tooltyp

**Comment by wangch079** [comment] 2023-09-19 05:36
>Maybe we need another column like, "Fetched"?

That's possible, and will require new fields in `.elastic-connectors-sync-jobs`.

>The confusion arises because the displayed numbers are "Document count" on index vs. "Docs added" (for each sync) implying we are counting the same thing - which is not the case!

No. "Document count" on index is the number of documents in the index atm. "Docs added" (for each sync) is the number of documents indexed in this sync. I think the confusion is that `Docs added` doesn't filter duplicated documents. E.g. If one document is indexed twice, `Docs added` will be 2 but actually, there's only one doc added. We can resolve this by introducing a set when counting, which may consume more memory for a large dataset. cc @danajuratoni let me know if you want to add it.

>investigate if there is a different way to display the numbers, so they are not confusing to the user

Add tooltips maybe.

Document count - The number of documents in the index at the moment
Docs added - The number of documents added to the index in the sync job
Docs removed - The number of documents removed from the index in the sync job

**Comment by seanstory** [comment] 2023-10-02 16:52
> We can resolve this by introducing a set when counting, which may consume more memory for a large dataset.

What about just parsing the response we get back from Elasticsearch _bulk request and doing our counting there? The response should tell us if a document was created or if an existing document was updated. That would also let us _not_ count any documents that had ingest pipeline failures and therefore weren't added OR updated.

**Comment by wangch079** [comment] 2023-10-10 06:15
>What about just parsing the response we get back from Elasticsearch _bulk request and doing our counting there?

@seanstory That's a great idea. Tested it and it worked. Will do so. Thank you.

cc @danajuratoni Let me know if you want to include this in 8.11.

**Comment by seanstory** [comment] 2023-10-10 16:23
There was another ticket (frontend) recently where we were realizing that the fields we're showing today may not be sufficient to give the full picture. If we could consider displaying more/different information, do you have thoughts on what it is that we should be counting and surfacing?

**Comment by wangch079** [comment] 2023-10-11 05:25
>do you have thoughts on what it is that we should be counting and surfacing?

The current stats available in sync job:

1. `indexed_document_count` - No of documents created and updated
2. `indexed_document_volume` - The volume of documents created and updated, without counting attachments 
3. `deleted_document_count` - No of documents deleted

I think what customers really care about is
1. how many new documents are added, proposing `created_document_count`
2. how many documents are updated, proposing `updated_document_count`. But this is not possible without utilizing a set because multiple operations of the same document will result in multiple `updated` responses.
3. `indexed_document_volume`, I think we can keep this. Do customers really care about the volume of documents created vs updated?
4. `deleted_document_count`, this can be kept.

**Comment by seanstory** [comment] 2023-10-11 19:46
To that list, I might suggest adding something like, `ignored_count`, which could cover documents that we fetch/see, but determine have not been changed and therefore do not need to be updated in Elasticsearch.

**Comment by wangch079** [comment] 2023-10-16 08:18
> To that list, I might suggest adding something like, `ignored_count`, which could cover documents that we fetch/see, but determine have not been changed and therefore do not need to be updated in Elasticsearch.

We do ignore some documents, if the `last_modified` timestamp doesn't change. But this also has some side effect. E.g. When a successful sync has been run, then the user enables advanced rules, and selects only fields a, b, and c, the d, the affected documents won't be updated.

If we are going to implement #4712 in the long run, I think we will remove the `last_modified` timestamp check.

**Comment by wangch079** [comment] 2024-04-29 14:48
I think this ticket can be closed with the counters work by @seanstory

**Comment by seanstory** [comment] 2024-05-03 14:22
Yep, closing this as a duplicate of https://github.com/elastic/enterprise-search-team/issues/4668. Thanks!

**Closed by seanstory** 2024-05-03 14:22 UTC
Labels: bug, sharepoint, effort:low, priority:medium
