### ISSUE TITLE
ApiError(429, 'TOO_MANY_REQUESTS') while indexing the records in Elasticsearch

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors#856] opened 2023-05-03 12:08 UTC
## Bug Description
Getting 429 too many requests error while indexing the sharepoint documents (large data set 2.5M) to elasticsearch

### To Reproduce
1. Take the latest code of main branch of github connectors-python repository
2. Do all the necessary configuration changes in config.yml file
3. On the Kibana, create an index > go to configuration tab > make config changes related to the sharepoint connector

## Expected behavior
All records should be properly indexed in Elasticsearch

## Actual behavior
429, too many requests error faced by the user as below and status of sync is Sync failure
`ApiError(429, "{'_shards': {'total': 2, 'successful': 0, 'failed': 2, 'failures': [{'shard': 0, 'index': '.elastic-connectors-v1', 'status': 'TOO_MANY_REQUESTS', 'reason': {'type': 'circuit_breaking_exception', 'reason': '[parent] Data too large, data for [indices:admin/refresh[s]] would be [1051923900/1003.1mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1051923680/1003.1mb], new bytes reserved: [220/220b], usages [model_inference=0/0b, inflight_requests=32840454/31.3mb, request=0/0b, fielddata=247/247b, eql_sequence=0/0b]', 'bytes_wanted': 1051923900, 'bytes_limit': 1020054732, 'durability': 'TRANSIENT'}}]}}")`

Only 138440 docs got indexed out of 250000 records

## Screenshots
<img width="1414" alt="Screen Shot 2023-05-03 at 5 22 47 PM" src="https://user-images.githubusercontent.com/103035276/235910706-acf05a5f-df81-4f5f-871b-5f0ac417990f.png">

Note - This test has been executed on sharepoint server. Attaching log files for more reference

- OS: CentOS 2 core CPU 18 GB RAM
[performance_GITHUB.log](https://github.com/elastic/connectors-python/files/11382235/performance_GITHUB.log)

**Comment by prashant-elastic** [comment] 2023-05-04 06:00
We also checked this on 8.8 branch of github and faced the same issue.

**Comment by danajuratoni** [comment] 2023-05-04 09:12
cc: @vidok

**Comment by artem-shelkovnikov** [comment] 2023-05-04 09:15
We don't handle this sort of throttling when uploading to Elasticsearch - the error says that Elasticsearch used all its memory to ingest data and for now cannot ingest more data and we need to wait.

We need to add this error handling into framework.

**Comment by artem-shelkovnikov** [comment] 2023-05-04 09:16
For now if you need to go on with your testing, just increase the memory available to Elasticsearch to double of your current value (I see you're allocating 1GB RAM to Elasticsearch which is too little)

**Comment by artem-shelkovnikov** [comment] 2023-05-04 15:37
@danajuratoni the problem is not Sharepoint-specific too, it's a framework issue

**Comment by prashant-elastic** [comment] 2023-05-05 08:06
Hey @artem-shelkovnikov Please find the screenshot attached which shows the configuration for the Elasticsearch cloud deployment that we used for testing. Do you recommend having an instance with any other configuration? 

![image (4)](https://user-images.githubusercontent.com/103035276/236406779-4c451b2b-37d6-45d4-b4d6-2e45d0c97c4f.png)

**Comment by artem-shelkovnikov** [comment] 2023-05-05 09:37
Hi @prashant-elastic, indeed - you can see that Master node is 1GB, you need to choose configuration with bigger master node if you want the error to go away while we're addressing the problem.

**Comment by prashant-elastic** [comment] 2023-05-08 05:45
Hoi @artem-shelkovnikov Sure, I will try configuring an instance with bigger master node.

**Comment by prashant-elastic** [comment] 2023-05-09 05:19
Hey @artem-shelkovnikov We tried looking for a way to configure an instance with bigger master node but did not find any luck. Can you please let us know from where to configure the same?

**Comment by ppf2** [comment] 2023-05-12 05:19
Try using 3 zones with 2G size per zone.

I thought we have some form of retry policy in place for backpressure from Elasticsearch on bulk indexing.  Based on the attached log file, is the bug here that the general retry mechanism is not working at the framework level?

**Comment by artem-shelkovnikov** [comment] 2023-05-15 08:35
> I thought we have some form of retry policy in place for backpressure from Elasticsearch on bulk indexing. Based on the attached log file, is the bug here that the general retry mechanism is not working at the framework level?

I think we don't have one at all or it's broken

**Comment by ppf2** [comment] 2023-05-15 22:55
Seems like it [retries 3 times with no delay](https://github.com/elastic/connectors-python/blob/main/connectors/es/client.py#L137) on everything except for conflict errors and gives up?

**Comment by artem-shelkovnikov** [comment] 2023-05-16 10:16
It retries 3 times only for conflict errors - only ConflictError is caught in `except` block, all other errors are just raised immediately

**Comment by ppf2** [comment] 2023-05-17 16:03
Here's an example retry policy for Elasticsearch bulk requests:

- Retry up to a threshold (or potentially indefinitely) on temporary unavailability of Elasticsearch (e.g. 429s and 503s)
- Do not retry 409s by default, or the current 3 retries is fine. Ensure that the problematic document is logged after the retries.
- Do not retry on permanent errors like 400 and 404 errors but ensure that information about the document that is dropped is logged

**Comment by artem-shelkovnikov** [comment] 2024-06-13 14:59
Closing as we've update backpressure logic to retry transparently

**Closed by artem-shelkovnikov** 2024-06-13 14:59 UTC
Labels: bug, sharepoint
