### ISSUE TITLE
JIRA connector: import Custom field names instead of IDs

### ISSUE THREAD

**Issue by Gleb-Gadyatskiy** [elastic/connectors#2415] opened 2024-04-20 16:08 UTC
### Problem Description
JIRA connector: please imports JIRA Custom fields names instead of their IDs. 
For now they are imported like "customfield_20311" (yes, in our JIRA we have a lot of them :) )
Which makes hard to process them later because need to manually map them to their real name (like "Environment name")

### Proposed Solution
User JIRA REST API like https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-fields/#api-group-issue-fields to retrieve human-readable Custom field names.

### Alternatives
Add human-readable Custom field name to each custom field object

**Comment by moxarth-elastic** [comment] 2024-04-29 09:24
@Gleb-Gadyatskiy I've addressed your suggestion through PR #2442. Can you please check it from your end?

**Comment by moxarth-elastic** [comment] 2024-05-01 05:49
@Gleb-Gadyatskiy did you get a chance to test the latest changes?

**Comment by praveen-elastic** [comment] 2024-05-01 12:18
We are closing the issue since the PR is merged, feel free to re-open if there are any concerns.

**Comment by Gleb-Gadyatskiy** [comment] 2024-05-01 12:34
Hi,
Cannot make synch working with elastic-connectors:8.13.2.1 Docker image:
(works fine for elastic-connectors:8.13.2.0 without latest changes)
`
2024-05-01 08:27:57 [FMWK][12:27:57][INFO] [Connector id: YWQWNI8Bst9ux8ILW4IL, index name: search-doc-peo-kb-jira, Sync job id: OWQfNI8Bst9ux8ILv4OD] Iterating on remote documents
2024-05-01 08:27:57 [FMWK][12:27:57][CRITICAL] [Connector id: YWQWNI8Bst9ux8ILW4IL, index name: search-doc-peo-kb-jira, Sync job id: OWQfNI8Bst9ux8ILv4OD] Document extractor failed
2024-05-01 08:27:57 Traceback (most recent call last):
2024-05-01 08:27:57   File "/app/connectors/es/sink.py", line 407, in run
2024-05-01 08:27:57     await self.get_docs(generator)
2024-05-01 08:27:57   File "/app/connectors/es/sink.py", line 458, in get_docs
2024-05-01 08:27:57     async for count, doc in aenumerate(generator):
2024-05-01 08:27:57   File "/app/connectors/utils.py", line 818, in aenumerate
2024-05-01 08:27:57     async for elem in asequence:
2024-05-01 08:27:57   File "/app/connectors/logger.py", line 176, in __anext__
2024-05-01 08:27:57     return await self.gen.__anext__()
2024-05-01 08:27:57   File "/app/connectors/es/sink.py", line 441, in _decorate_with_metrics_span
2024-05-01 08:27:57     async for doc in generator:
2024-05-01 08:27:57   File "/app/connectors/sync_job_runner.py", line 411, in prepare_docs
2024-05-01 08:27:57     async for doc, lazy_download, operation in self.generator():
2024-05-01 08:27:57   File "/app/connectors/sync_job_runner.py", line 447, in generator
2024-05-01 08:27:57     async for doc, lazy_download in self.data_provider.get_docs(
2024-05-01 08:27:57   File "/app/connectors/sources/jira.py", line 1012, in get_docs
2024-05-01 08:27:57     self.custom_fields = await self.jira_client.get_jira_fields()
2024-05-01 08:27:57   File "/app/connectors/sources/jira.py", line 420, in get_jira_fields
2024-05-01 08:27:57     jira_fields = await response.json()
2024-05-01 08:27:57   File "/app/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1160, in json
2024-05-01 08:27:57     await self.read()
2024-05-01 08:27:57   File "/app/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1100, in read
2024-05-01 08:27:57     self._body = await self.content.read()
2024-05-01 08:27:57   File "/app/lib/python3.10/site-packages/aiohttp/streams.py", line 373, in read
2024-05-01 08:27:57     block = await self.readany()
2024-05-01 08:27:57   File "/app/lib/python3.10/site-packages/aiohttp/streams.py", line 395, in readany
2024-05-01 08:27:57     await self._wait("readany")
2024-05-01 08:27:57   File "/app/lib/python3.10/site-packages/aiohttp/streams.py", line 302, in _wait
2024-05-01 08:27:57     await waiter
2024-05-01 08:27:57 aiohttp.client_exceptions.ClientConnectionError: Connection closed
2024-05-01 08:27:58 [FMWK][12:27:58][INFO] [Connector id: YWQWNI8Bst9ux8ILW4IL, index name: search-doc-peo-kb-jira, Sync job id: OWQfNI8Bst9ux8ILv4OD] Sync ended with status error -- created: 0 | updated: 0 | deleted: 0 (took 2 seconds)
`

**Comment by Gleb-Gadyatskiy** [comment] 2024-05-01 16:58
but cannot see any change in Custom fields :(

**Comment by Gleb-Gadyatskiy** [comment] 2024-05-01 23:44
I applied new jira.py to [docker.elastic.co/enterprise-search/elastic-connectors:8.13.2.1] and it fails with this error. Original jyre.py from [docker.elastic.co/enterprise-search/elastic-connectors:8.13.2.1] works fine (but no custom field names)

> 2024-05-01 19:42:03 [FMWK][23:42:03][CRITICAL] [Connector id: 32R7No8Bst9ux8IL_ruX, index name: search-doc-peo-kb-jira, Sync job id: I2SJNo8Bst9ux8ILUr0L] Document extractor failed
> 2024-05-01 19:42:03 Traceback (most recent call last):
> 2024-05-01 19:42:03   File "/app/connectors/es/sink.py", line 407, in run
> 2024-05-01 19:42:03     await self.get_docs(generator)
> 2024-05-01 19:42:03   File "/app/connectors/es/sink.py", line 458, in get_docs
> 2024-05-01 19:42:03     async for count, doc in aenumerate(generator):
> 2024-05-01 19:42:03   File "/app/connectors/utils.py", line 818, in aenumerate
> 2024-05-01 19:42:03     async for elem in asequence:
> 2024-05-01 19:42:03   File "/app/connectors/logger.py", line 176, in __anext__
> 2024-05-01 19:42:03     return await self.gen.__anext__()
> 2024-05-01 19:42:03   File "/app/connectors/es/sink.py", line 441, in _decorate_with_metrics_span
> 2024-05-01 19:42:03     async for doc in generator:
> 2024-05-01 19:42:03   File "/app/connectors/sync_job_runner.py", line 411, in prepare_docs
> 2024-05-01 19:42:03     async for doc, lazy_download, operation in self.generator():
> 2024-05-01 19:42:03   File "/app/connectors/sync_job_runner.py", line 447, in generator
> 2024-05-01 19:42:03     async for doc, lazy_download in self.data_provider.get_docs(
> 2024-05-01 19:42:03   File "/app/connectors/sources/jira.py", line 1012, in get_docs
> 2024-05-01 19:42:03     self.custom_fields = await self.jira_client.get_jira_fields()
> 2024-05-01 19:42:03   File "/app/connectors/sources/jira.py", line 420, in get_jira_fields
> 2024-05-01 19:42:03     jira_fields = await response.json()
> 2024-05-01 19:42:03   File "/app/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1160, in json
> 2024-05-01 19:42:03     await self.read()
> 2024-05-01 19:42:03   File "/app/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1100, in read
> 2024-05-01 19:42:03     self._body = await self.content.read()
> 2024-05-01 19:42:03   File "/app/lib/python3.10/site-packages/aiohttp/streams.py", line 373, in read
> 2024-05-01 19:42:03     block = await self.readany()
> 2024-05-01 19:42:03   File "/app/lib/python3.10/site-packages/aiohttp/streams.py", line 395, in readany
> 2024-05-01 19:42:03     await self._wait("readany")
> 2024-05-01 19:42:03   File "/app/lib/python3.10/site-packages/aiohttp/streams.py", line 302, in _wait
> 2024-05-01 19:42:03     await waiter
> 2024-05-01 19:42:03 aiohttp.client_exceptions.ClientConnectionError: Connection closed
> 2024-05-01 19:42:04 [FMWK][23:42:04][INFO] [Connector id: 32R7No8Bst9ux8IL_ruX, index name: search-doc-peo-kb-jira, Sync job id: I2SJNo8Bst9ux8ILUr0L] Sync ended with status error -- created: 0 | updated: 0 | deleted: 0 (took 1 seconds)

**Comment by moxarth-elastic** [comment] 2024-05-02 06:41
@Gleb-Gadyatskiy I've verified the changes for Jira cloud and data center, it seems to be working fine for us. Could you please try to run the connector from `main` branch once and confirm if you still face this issue?

**Comment by Gleb-Gadyatskiy** [comment] 2024-05-02 12:18
I repeated test using jira.py from main branch (and Docker image as code base) - same error. Our JIRA server is slow, can it causes the issue?

>   elastic-connector:
>     image: docker.elastic.co/enterprise-search/elastic-connectors:8.13.2.1
>     command: /app/bin/elastic-ingest -c /config/config.yml
>     depends_on:
>       - es01
>     networks:
>       - elastic
>     volumes:
>       - ./docker/connector/confluence-config.yml:/config/config.yml:ro
>       - ./docker/connector/jira.py:/app/connectors/sources/jira.py:ro

**Comment by moxarth-elastic** [comment] 2024-05-02 17:20
> Our JIRA server is slow, can it causes the issue?

Probably yes, if the Jira server is slow to respond, the request might time out before a successful connection is established, resulting in a ClientConnectionError.
I also wonder if it's an issue of slow server, we could have faced it in older code as well. 
Even i am not able to reproduce the issue either with jira cloud or data center!! Do you have another jira server to confirm if it's a server issue?

**Comment by Gleb-Gadyatskiy** [comment] 2024-05-02 21:27
If I use original jira.py from elastic-connectors:8.13.2.1 - the import runs fine, without ClientConnectionError. 
I suspect that the connection may not be ready at moment get_jira_fields (line 420) gets executed. It is possible?

**Comment by Gleb-Gadyatskiy** [comment] 2024-05-03 03:45
I also replaced 
> self.custom_fields = await self.jira_client.get_jira_fields()
by
>self.custom_fields = {}
and the import runs without errors (and without custom fields)

**Comment by moxarth-elastic** [comment] 2024-05-03 05:13
Strange!! 🤯 
I've made a change to `get_jira_fields` method if that can resolve your issue, could you please try to check it on this commit - https://github.com/elastic/connectors/commit/390c803b8c80200fb0c01422438a83f0059b75ae?

**Comment by Gleb-Gadyatskiy** [comment] 2024-05-03 13:57
wow, it works! much better now, all Custom named are in place.
May I propose one last change - because custom field names now may conflict with regular - let put custom fields in a child object (like "custom")?

**Comment by moxarth-elastic** [comment] 2024-05-06 07:13
> wow, it works! much better now, all Custom names are in place. May I propose one last change - because custom field names now may conflict with regular - let put custom fields in a child object (like "custom")?

That's great!
I've raised a PR for the proposed change.

**Closed** 2024-05-09 06:07 UTC
Labels: enhancement, jira, team:external, community-driven
