### ISSUE TITLE
[MySQL] Advanced rules don't support renaming pkey columns

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#1760] opened 2023-10-10 11:52 UTC
## Bug Description

Advanced rules for mysql don't support renaming primary key columns in SELECT statement. It leads to almost empty result set. (just 1 result)

### To Reproduce
1. Sestup local mysql with table users and orders

```
CREATE TABLE mydb.users (
  id INT PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255)
);
```

```
CREATE TABLE mydb.orders (
  order_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  product_name VARCHAR(255),
  order_date DATE,
  FOREIGN KEY (user_id) REFERENCES mydb.users(id)
);
```
Ask some LLM to generate some dummy data that is joinable.

2. Create mysql connector
3. Add advenced sync rule
```
[
  {
    "tables": [
      "users",
      "orders"
    ],
    "query": "SELECT users.id AS u_id, orders.order_id AS o_id, users.name AS user_name, orders.product_name AS product_name, orders.order_date AS order_date FROM users JOIN orders ON users.id = orders.user_id"
  }
]
```

4. Run sync

5. There will be only one document with weird looking `id` field, something like:
<img width="589" alt="Screenshot 2023-10-10 at 13 49 46" src="https://github.com/elastic/connectors-python/assets/14121688/96aa0fb2-cb01-46f7-9937-303cb87b4673">

6. The issue is with `generate_id` in mysql connector that gets `column_names` that are taken from table schema, while the `row` has renamed columns.

The id generation logic should take this edge case into account.

## Expected behavior

The advanced sync rule should return query result. The result is correct if I don't rename primary column names:

```
[
  {
    "tables": [
      "users",
      "orders"
    ],
    "query": "SELECT users.id AS id, orders.order_id AS order_id, users.name AS user_name, orders.product_name AS product_name, orders.order_date AS order_date FROM users JOIN orders ON users.id = orders.user_id"
  }
]
```

The key part is: `users.id AS id, orders.order_id AS order_id`

With this advanced rule everything works as expected. (no renaming of

**Comment by parthpuri-elastic** [comment] 2024-07-18 06:15
Hi @jedrazb, I have checked this issue, but the problem is, after renaming the PK, table records will get changed, but when we are fetching PK, we got the original name, so we are not able to find a new PK from the response. However now we are adding new `id_columns` field in all database connector for generating IDs if PK is missing. So after changing the PK name user can add that new name in `id_columns` fields this will potentially fix this issue. WDYT?

**Comment by moxarth-elastic** [comment] 2024-08-22 05:15
> Hi @jedrazb, I have checked this issue, but the problem is, after renaming the PK, table records will get changed, but when we are fetching PK, we got the original name, so we are not able to find a new PK from the response. However, in this [PR](https://github.com/elastic/connectors/pull/2696), now we are adding new `id_columns` field in all database connector for generating IDs if PK is missing. So after changing the PK name user can add that new name in `id_columns` fields this will potentially fix this issue. WDYT?

@jedrazb do you have any suggestion over this or we can close this issue since the PR is merged?

**Closed** 2024-08-27 09:02 UTC
Labels: bug, mysql, tech-debt, team:external, effort:low, priority:low, tech-improvement
