### ISSUE TITLE
Facing AuthorizationException Error while running native connectors on 8.13.0 elastic deployment

### ISSUE THREAD

**Issue by kajal-elastic** [elastic/connectors#2193] opened 2024-02-20 12:18 UTC
## Bug Description
Facing AuthorizationException Error while running native connectors on 8.13.0 elastic deployment

### To Reproduce
1. Go to Connectors - > Native connectors 
2. Click on any of the connectors (for instance: Google Cloud Storage, Azure Blob Storage, Jira) and Create a connector by specifying a name 
3. Attach an index to the connector 
4. Enter Configuration values for the connector and refresh the page
5. Click on Sync -> Full Sync
6. Observe the error displayed on Connector overview page

## Expected behavior
Sync should be executed successfully and all the data present in the source should get indexed

## Actual behavior
Sync fails and 403 AuthorizationException is faced. 

Error :
 
Sync failure: AuthorizationException: AuthorizationException(403, 'security_exception', 'action [indices:data/read/search] is unauthorized for user [cloud-internal-enterprise_search-server] with effective roles [cloud-internal-enterprise_search-server,kibana_system] on indices [gcs], this action is granted by the index privileges [read,all]').

## Screenshots
![AuthorizationException](https://github.com/elastic/connectors/assets/152139266/4c69e3e9-c39d-4e4f-a7a6-99d870c79545)

## Environment
Elastic Deployment : 8.13.0(latest)

## Additional context
This was tested on 8.13.0 elastic deployment BC1

**Comment by seanstory** [comment] 2024-03-04 15:10
@navarone-feekery this looks like something isn't working right with indices not prefixed with `search` as native connectors. 

@kajal-elastic does this happen on a fresh Cloud deployment for 8.13.0-SNAPSHOT?

**Comment by navarone-feekery** [comment] 2024-03-04 15:13
Hi @kajal-elastic, was this on the BC1 for 8.13? This is resolved now as of BC2. Can you test this again on a new instance?

**Comment by navarone-feekery** [comment] 2024-03-04 15:15
Ah I see the comment now that this was BC1 -- I'm sure the fix is in, but I'd like a confirmation from you that you can create and sync native connectors before I close.

**Comment by navarone-feekery** [comment] 2024-03-04 15:28
The fix is in this PR and I confirmed it's working in BC3: https://github.com/elastic/connectors/pull/2196
Closing

**Closed by navarone-feekery** 2024-03-04 15:28 UTC
Labels: bug
